#!/bin/bash

jq -r '.[] | [(.toolName), (.commands | join("\n") | @sh) ] | @tsv' tools.json | while IFS=$'\t' read -r toolName toolCommands; do
	./scripts/installTool "$toolName" "$toolCommands"
	# sleep until everything is ok after
	# while [ -e /var/lib/apt/lists/lock ]; do
	sleep 3
	# done
done
